### ISSUE TITLE
Некорректное отображение даты последнего посещения для нулевого VisitedAt

### ISSUE THREAD

**Issue by yamnikov-oleg** [13pinj/todoapp#2]
В админке рядом с пользователями, ни разу не посещавшими сайт со времени введения колонки `users.visited_at`, отображается нулевая дата последнего посещения: `был 01.01.0001`.

Одно из решений: подменять нулевой VisitedAt на CreatedAt.
Когда это можно сделать:
* При запуске сервера, когда происходит миграция таблицы, обновить соответствующие записи в базе.
* При загрузке записи из базы, через коллбек, предоставляемый gorm'ом.
* При обращении к колонке в шаблонах: обернуть прямое получение поля в функцию, возвращающую CreatedAt при случае.

**Comment by DeFiXiK** [comment]
- Если пользователь не заходил больше 5 месяцев, можно предположить что он забил на сайт и сделать отметку `был давно` - или что-то в этом роде. 
- А записи в базе обновить первым способом, это будет оптимально.

**Comment by yamnikov-oleg** [comment]
Я как раз выбрал первый способ, к вечеру залью код.

А насчет `был давно`: на данный момент вьюха выводит дату последнего посещения для пользователей, которых давно не было больше 2 дней. По-моему это более информативное решение.
